ARG NUCLIO_LABEL=1.5.11

FROM node:10.23 as build-static

WORKDIR /home/nuclio/dashboard/src
# copy source tree
COPY ./pkg/dashboard/ui/package*.json ./

# install gulp and bower, cd into the source dir and build to create /home/nuclio/dashboard/src/dist
# which contains all the necessary files (index.html and assets/ dir)
RUN set -ex \
#           && npm config set registry  "http://registry.npm.taobao.org/" \
           && npm config list \
           && npm install -g gulp \
           && cd /home/nuclio/dashboard/src \
           && rm -rf ./dist ./node_modules ./resources/*/node_modules \
            && npm install --production 
